# Utilizando o DataFrame

In [1]:
import pandas as pd

In [3]:
dados = {
    'Nome' : ['Alice', 'Bob', 'Charile'],
    'Idade' : [ 24, 30, 22],
    'Cidade' : ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte']
}

In [6]:
df = pd.DataFrame(dados)
df

      Nome  Idade          Cidade
0    Alice     24       São Paulo
1      Bob     30  Rio de Janeiro
2  Charile     22  Belo Horizonte

In [ ]:
# o .head trás as 5 primeiras linhas de um dataframe, se quiser puxar alguma linha especifica. só colocar o numero entre parenteses
df.head()

      Nome  Idade          Cidade
0    Alice     24       São Paulo
1      Bob     30  Rio de Janeiro
2  Charile     22  Belo Horizonte

In [11]:
# .tail puxa as 5 ultimas linhas do dataFrame
df.tail(1)

      Nome  Idade          Cidade
2  Charile     22  Belo Horizonte

In [22]:
dados_notas = {
    'Nome' : ['Alice', 'Charlie', 'David', 'Eva', 'Bob'],
    'Matemática': [8.0, 8.5, 7.5, 9.0, 10.0],
    'Física' : [7.5, 8.0, 6.7, 8.5, 9.5],
    'Química' : [8.5, 7.5, 8.0, 9.0, 10.0]
    }
dados_notas

{'Nome': ['Alice', 'Charlie', 'David', 'Eva', 'Bob'],
 'Matemática': [8.0, 8.5, 7.5, 9.0, 10.0],
 'Física': [7.5, 8.0, 6.7, 8.5, 9.5],
 'Química': [8.5, 7.5, 8.0, 9.0, 10.0]}

In [23]:
df_notas = pd.DataFrame(dados_notas)
df_notas

      Nome  Matemática  Física  Química
0    Alice         8.0     7.5      8.5
1  Charlie         8.5     8.0      7.5
2    David         7.5     6.7      8.0
3      Eva         9.0     8.5      9.0
4      Bob        10.0     9.5     10.0

In [26]:
# Calculando a média dos alunos
df_notas['Média'] = df_notas[['Matemática', 'Física', 'Química']].mean(axis=1)
df_notas

      Nome  Matemática  Física  Química     Média
0    Alice         8.0     7.5      8.5  8.000000
1  Charlie         8.5     8.0      7.5  8.000000
2    David         7.5     6.7      8.0  7.400000
3      Eva         9.0     8.5      9.0  8.833333
4      Bob        10.0     9.5     10.0  9.833333

In [27]:
# Identificar alunos aprovados com nota maior que 8.5
alunos_aprovados = df_notas[df_notas['Média'] >= 8.5]
alunos_aprovados

  Nome  Matemática  Física  Química     Média
3  Eva         9.0     8.5      9.0  8.833333
4  Bob        10.0     9.5     10.0  9.833333

In [28]:
# Exibir a média e os alunos aprovados
df_notas[['Nome', 'Média']]

      Nome     Média
0    Alice  8.000000
1  Charlie  8.000000
2    David  7.400000
3      Eva  8.833333
4      Bob  9.833333

In [29]:
# Exbir alunos aprovados mostrado só a média e o nome

alunos_aprovados[['Nome', 'Média']]

  Nome     Média
3  Eva  8.833333
4  Bob  9.833333